### ISSUE TITLE
Some explanation.

### ISSUE THREAD

**Issue by nedievas** [vigasan/SecutityAlarm#3]
Could you explain what is this?
![Screenshot from 2023-06-13 22-54-21](https://github.com/vigasan/SecutityAlarm/assets/6176288/6f95d3e4-6436-447c-af15-57a589deb59c)
I have nearly designed all the scheme in EasyEDA, left only this.

**Comment by vigasan** [comment]
This is JTAG connector for microcontroller programming and debugging

**Comment by nedievas** [comment]
Thanks. I suppose P1 is the same connector?

**Comment by nedievas** [comment]
One more question:
Is that correct (+13.8):
![Screenshot from 2023-06-14 20-12-03](https://github.com/vigasan/SecutityAlarm/assets/6176288/0001d5c0-e1ef-454f-901e-3cbe9c9dd9b2)

as to your reference: ![Screenshot from 2023-06-14 20-10-09](https://github.com/vigasan/SecutityAlarm/assets/6176288/4a19faf4-92a4-4c19-acca-14b0f91d1566)
I get [Info] : The name of the Netport $3I63 does not match the name of the connected Wire.

**Comment by vigasan** [comment]
P1 is connector to program ESP32.
+13.8 is the voltage you need to charge lead acid battery.

**Comment by nedievas** [comment]
> P1 is connector to program ESP32. +13.8 is the voltage you need to charge lead acid battery.

I do understand +13.8, but is this correct connection in my schematics, as I do not have repeat script, I had to do it manually. I connect +13.8 to K_CM1, but do not connect to K_CM2 up to K_CM7?

Do you have higher resolution image of PCB? Youtube is not clear.

**Comment by vigasan** [comment]
Yes, it's correct. I used only K1 relay for 13.8V, other relays have COMMON pin free
